dist: trusty
sudo: required
services:
  - docker
language: python
matrix:
  include:
    - python: 2.6
    - python: 2.7
    - python: 3.4
    - python: 3.5
#install:
#  - pip install dbus-python
#  - pip install python-utmp
script:
  - make test
after_success:
  - coveralls
#notifications:
#  irc:
#    channels:
#      - "chat.freenode.net#ansible-notices"
#    on_success: change
#    on_failure: always
#    skip_join: true
#    nick: ansibletravis